import React from 'react';
import { FileText, Cpu, Bot, Briefcase, LineChart, GraduationCap, Sparkles } from 'lucide-react';

const Features = () => {
  const featuresList = [
    {
      title: "AI Resume Analyzer",
      description: "Upload your resume and get instant AI-powered recommendations on keywords, formatting, and structural improvements to stand out.",
      icon: <FileText className="w-8 h-8 text-violet-600" />,
      badgeColor: "bg-violet-50 border-violet-100",
      link: "/analyzer"
    },
    {
      title: "ATS Score Checker",
      description: "Match your resume with targeted job descriptions and predict your Applicant Tracking System score to bypass automated filters.",
      icon: <Cpu className="w-8 h-8 text-blue-500" />,
      badgeColor: "bg-blue-50 border-blue-100",
      link: "/analyzer"
    },
    {
      title: "AI Mock Interviews",
      description: "Practice answering customized, role-specific questions generated by our AI and receive real-time feedback on your answers.",
      icon: <Bot className="w-8 h-8 text-emerald-500" />,
      badgeColor: "bg-emerald-50 border-emerald-100",
      link: "/auth/signup"
    },
    {
      title: "Smart Job Matcher",
      description: "Get curated job and internship recommendations tailored to your profile, skill levels, academic background, and interests.",
      icon: <Briefcase className="w-8 h-8 text-amber-500" />,
      badgeColor: "bg-amber-50 border-amber-100",
      link: "/jobs"
    },
    {
      title: "Application Tracker",
      description: "Organize and track all your ongoing job applications from first contact to interview stage and final offer in one clean dashboard.",
      icon: <LineChart className="w-8 h-8 text-pink-500" />,
      badgeColor: "bg-pink-50 border-pink-100",
      link: "/auth/signup"
    },
    {
      title: "Skill Gap Analysis",
      description: "Discover what skills are missing in your profile compared to current market requirements and get smart course recommendations.",
      icon: <GraduationCap className="w-8 h-8 text-violet-500" />,
      badgeColor: "bg-violet-50 border-violet-100",
      link: "/auth/signup"
    }
  ];

  return (
    <section id="features" className="py-20 sm:py-24 bg-violet-50 overflow-hidden scroll-mt-16">
      <div className="max-w-7xl mx-auto px-4">
        
        {/* Header Section */}
        <div className="text-center space-y-4 mb-16 sm:mb-20 px-4 animate-fade-up">
          <div className="inline-flex items-center gap-2 bg-violet-50 text-violet-600 px-4 py-2 rounded-full text-xs font-bold border border-violet-100">
            <Sparkles size={14} className="fill-violet-600 animate-pulse" />
            <span>Powerhouse Platform Capabilities</span>
          </div>
          <h2 className="text-3xl sm:text-5xl lg:text-6xl font-black text-gray-900 tracking-tight leading-tight">
            Features Tailored for <span className="text-violet-600">Your Success</span>
          </h2>
          <p className="text-sm sm:text-base text-gray-500 font-medium max-w-2xl mx-auto leading-relaxed">
            From crafting the perfect ATS-friendly resume to tracking applications and preparing for interviews, CareerSync AI equips you with everything needed to land your dream role.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {featuresList.map((feature, index) => (
            <div 
              key={index}
              className="bg-white border border-gray-100 hover:border-violet-100 p-8 rounded-[32px] shadow-sm hover:shadow-xl hover:shadow-violet-900/5 transition-all duration-300 group flex flex-col justify-between"
            >
              <div className="space-y-6">
                {/* Icon Badge */}
                <div className={`w-16 h-16 rounded-2xl border ${feature.badgeColor} flex items-center justify-center transition-all duration-300 group-hover:scale-110 group-hover:shadow-md`}>
                  {feature.icon}
                </div>

                {/* Content */}
                <div className="space-y-3">
                  <h3 className="text-xl font-extrabold text-gray-950 transition-colors group-hover:text-violet-600">
                    {feature.title}
                  </h3>
                  <p className="text-gray-500 text-sm font-medium leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </div>

              {/* Action Link */}
              <div className="pt-6">
                <a 
                  href={feature.link}
                  className="inline-flex items-center gap-2 text-sm font-bold text-violet-600 hover:text-violet-700 transition-colors"
                >
                  Explore feature &rarr;
                </a>
              </div>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
};

export default Features;
