"use client";

import React, { useState, useEffect, useRef } from 'react';
import { Sparkles, MessageSquare, Briefcase, Mic, MicOff, Send, XCircle, ChevronLeft } from 'lucide-react';
import axios from 'axios';
import toast from 'react-hot-toast';

export default function MockInterviewPage() {
  const [mode, setMode] = useState('setup'); // 'setup' | 'chat'
  const [jobRole, setJobRole] = useState('Frontend Engineer');
  const [interviewType, setInterviewType] = useState('Technical');
  
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  
  const [isRecording, setIsRecording] = useState(false);
  const recognitionRef = useRef(null);
  const messagesEndRef = useRef(null);

  useEffect(() => {
    // Scroll to bottom when messages change
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, isTyping]);

  useEffect(() => {
    // Initialize Speech Recognition if supported
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (SpeechRecognition) {
      const recognition = new SpeechRecognition();
      recognition.continuous = true;
      recognition.interimResults = true;
      recognition.lang = 'en-US';

      recognition.onresult = (event) => {
        let currentTranscript = '';
        for (let i = event.resultIndex; i < event.results.length; i++) {
          const transcript = event.results[i][0].transcript;
          if (event.results[i].isFinal) {
            setInputValue(prev => prev + transcript + ' ');
          } else {
            currentTranscript += transcript;
          }
        }
      };

      recognition.onerror = (event) => {
        console.error("Speech recognition error", event.error);
        setIsRecording(false);
      };

      recognition.onend = () => {
        setIsRecording(false);
      };

      recognitionRef.current = recognition;
    }
  }, []);

  const toggleRecording = () => {
    if (!recognitionRef.current) {
      toast.error("Speech recognition is not supported in this browser.");
      return;
    }
    if (isRecording) {
      recognitionRef.current.stop();
    } else {
      recognitionRef.current.start();
      setIsRecording(true);
    }
  };

  const startInterview = async () => {
    if (!jobRole.trim()) {
      toast.error("Please enter a job role.");
      return;
    }
    setMode('chat');
    setMessages([]);
    
    // Initial bot message is generated by sending a system prompt disguised as the first user message
    // but we can just send an initial "Hello" from the user behind the scenes
    await sendMessage("Hello, I am ready to start the interview.");
  };

  const sendMessage = async (textOverride) => {
    const text = textOverride || inputValue.trim();
    if (!text) return;

    // Add user message to UI
    const userMsg = { role: 'user', text };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInputValue('');
    if (isRecording) {
      recognitionRef.current?.stop();
    }

    // Call API
    setIsTyping(true);
    try {
      const token = localStorage.getItem("token");
      const response = await axios.post(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}/api/interview/chat`, {
        messages: newMessages,
        jobRole,
        interviewType
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });

      setMessages([...newMessages, { role: 'model', text: response.data.text }]);
    } catch (err) {
      console.error(err);
      toast.error("Failed to get response from interviewer.");
    } finally {
      setIsTyping(false);
    }
  };

  return (
    <div className="animate-fade-up min-h-[calc(100vh-120px)] flex flex-col">
      <div className="mb-8 shrink-0">
        <h1 className="text-[2.5rem] font-extrabold mb-2 text-slate-900 tracking-tight flex items-center gap-3">
          <MessageSquare className="text-violet-600" size={36} />
          AI Mock Interview Simulator
        </h1>
        <p className="text-slate-500 text-[1.1rem]">Practice your interview skills with our real-time AI interviewer.</p>
      </div>

      {mode === 'setup' && (
        <div className="bg-white border border-slate-200 rounded-3xl p-10 shadow-[0_10px_25px_rgba(0,0,0,0.02)] max-w-2xl mx-auto w-full text-center mt-10">
          <div className="w-20 h-20 bg-violet-100 text-violet-600 rounded-full flex items-center justify-center mx-auto mb-6">
            <Briefcase size={40} />
          </div>
          <h2 className="text-2xl font-bold text-slate-900 mb-8">Setup Your Mock Interview</h2>
          
          <div className="space-y-6 text-left max-w-sm mx-auto mb-10">
            <div>
              <label className="block text-sm font-bold text-slate-700 mb-2">Target Job Role</label>
              <input 
                type="text" 
                value={jobRole}
                onChange={(e) => setJobRole(e.target.value)}
                placeholder="e.g. Frontend Developer"
                className="w-full bg-slate-50 border border-slate-200 px-4 py-3 rounded-xl focus:outline-none focus:border-violet-600 font-medium"
              />
            </div>
            
            <div>
              <label className="block text-sm font-bold text-slate-700 mb-2">Interview Type</label>
              <div className="flex gap-4">
                <button 
                  onClick={() => setInterviewType('Technical')}
                  className={`flex-1 py-3 rounded-xl font-bold transition-all border-2 ${interviewType === 'Technical' ? 'border-violet-600 bg-violet-50 text-violet-700' : 'border-slate-200 bg-white text-slate-500'}`}
                >
                  Technical
                </button>
                <button 
                  onClick={() => setInterviewType('HR')}
                  className={`flex-1 py-3 rounded-xl font-bold transition-all border-2 ${interviewType === 'HR' ? 'border-violet-600 bg-violet-50 text-violet-700' : 'border-slate-200 bg-white text-slate-500'}`}
                >
                  HR / Behavioral
                </button>
              </div>
            </div>
          </div>

          <button 
            onClick={startInterview}
            className="bg-gradient-to-r from-violet-600 to-indigo-600 text-white px-8 py-4 rounded-2xl font-bold transition-all shadow-lg shadow-violet-600/30 hover:-translate-y-1 hover:shadow-violet-600/40 inline-flex items-center gap-3 text-lg w-full max-w-sm"
          >
            <Sparkles size={22} /> Start Simulator
          </button>
        </div>
      )}

      {mode === 'chat' && (
        <div className="bg-white border border-slate-200 rounded-3xl shadow-[0_10px_25px_rgba(0,0,0,0.02)] w-full max-w-4xl mx-auto flex flex-col flex-1 max-h-[800px] overflow-hidden">
          
          {/* Chat Header */}
          <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50 shrink-0">
            <div className="flex items-center gap-4">
              <button onClick={() => setMode('setup')} className="text-slate-400 hover:text-slate-900 transition-colors">
                <ChevronLeft size={24} />
              </button>
              <div>
                <h3 className="font-bold text-slate-900 text-lg">AI Interviewer</h3>
                <p className="text-xs font-semibold text-violet-600 uppercase tracking-wider">{jobRole} • {interviewType}</p>
              </div>
            </div>
            <button 
              onClick={() => sendMessage("I would like to end the interview now. Please provide feedback.")}
              className="text-sm font-bold text-rose-500 bg-rose-50 px-4 py-2 rounded-lg hover:bg-rose-100 transition-colors"
            >
              End & Get Feedback
            </button>
          </div>

          {/* Chat History */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar bg-slate-50/50">
            {messages.filter(m => !m.text.startsWith('Hello, I am ready')).map((msg, idx) => (
              <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[80%] rounded-2xl p-4 shadow-sm ${msg.role === 'user' ? 'bg-violet-600 text-white rounded-tr-sm' : 'bg-white border border-slate-200 text-slate-800 rounded-tl-sm'}`}>
                  <p className="whitespace-pre-wrap leading-relaxed">{msg.text}</p>
                </div>
              </div>
            ))}
            {isTyping && (
              <div className="flex justify-start">
                <div className="bg-white border border-slate-200 rounded-2xl p-4 rounded-tl-sm shadow-sm flex items-center gap-2">
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce"></div>
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '0.4s' }}></div>
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Chat Input */}
          <div className="p-4 sm:p-6 border-t border-slate-100 bg-white shrink-0">
            <div className="flex items-center gap-3">
              <button 
                onClick={toggleRecording}
                className={`p-4 rounded-full transition-all shrink-0 ${isRecording ? 'bg-rose-100 text-rose-600 animate-pulse' : 'bg-slate-100 text-slate-500 hover:bg-slate-200'}`}
                title="Use Microphone"
              >
                {isRecording ? <Mic size={24} /> : <MicOff size={24} />}
              </button>
              
              <div className="flex-1 relative">
                <textarea 
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      sendMessage();
                    }
                  }}
                  placeholder={isRecording ? "Listening..." : "Type your answer..."}
                  className="w-full bg-slate-50 border border-slate-200 rounded-2xl pl-5 pr-14 py-4 focus:outline-none focus:border-violet-600 focus:bg-white resize-none h-14 min-h-[56px] max-h-32 custom-scrollbar"
                  rows={1}
                />
                <button 
                  onClick={() => sendMessage()}
                  disabled={!inputValue.trim()}
                  className="absolute right-3 top-1/2 -translate-y-1/2 bg-violet-600 text-white p-2 rounded-xl disabled:opacity-50 disabled:bg-slate-300 transition-colors"
                >
                  <Send size={18} />
                </button>
              </div>
            </div>
            <div className="text-center mt-3 text-xs text-slate-400 font-medium">
              You can type your answer or use the microphone icon to speak.
            </div>
          </div>

        </div>
      )}

    </div>
  );
}
